# Generated by Django 2.2 on 2019-04-05 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poiclass',
            options={'verbose_name': 'POIClass', 'verbose_name_plural': 'POIClasses'},
        ),
        migrations.AlterModelTable(
            name='poiclass',
            table='POIClass',
        ),
    ]
