# Generated by Django 2.2 on 2019-04-05 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0002_auto_20190405_1951'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Adventure & Outdoors', 'Adventure & Outdoors'), ('Pilgrimage', 'Pilgrimage'), ('Chill & Relax', 'Chill & Relax'), ('Spiritual & Heritage', 'Spiritual & Heritage'), ('Work & Travel', 'Work & Travel'), ('Social Tourism (Volunteer & Travel)', 'Social Tourism (Volunteer & Travel)')], max_length=20, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='poiclass',
            name='filters',
            field=models.ManyToManyField(help_text='Department of this user.', to='interface.Filter'),
        ),
    ]
