# Generated by Django 2.2 on 2019-04-05 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0003_auto_20190405_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='name',
            field=models.CharField(choices=[('Adventure & Outdoors', 'Adventure & Outdoors'), ('Pilgrimage', 'Pilgrimage'), ('Chill & Relax', 'Chill & Relax'), ('Spiritual & Heritage', 'Spiritual & Heritage'), ('Work & Travel', 'Work & Travel'), ('Social Tourism (Volunteer & Travel)', 'Social Tourism (Volunteer & Travel)')], max_length=50, unique=True),
        ),
    ]
